"""Refuses samples that were themselves written by a model.

The gate at the other end. Gates 1 to 3 guard what leaves; this guards what comes
in, and the reason is simple arithmetic: a voice profile built from AI-generated
text teaches the drafting agent to sound like an AI. The applicant would end up
with a machine imitating a machine imitating them, and the whole promise of the
product -- that the packet sounds like the person -- quietly stops being true.

This is a judgement, not a measurement. No detector can prove authorship. So the
verdict always carries the specific markers it was made on, in the applicant's own
sample, and the refusal quotes them. A person who disagrees can see exactly what
was read and give a different sample.
"""

from __future__ import annotations

from google.adk.agents import Agent
from google.genai import types
from pydantic import BaseModel, Field

from berkas.runtime import model_id, run_json


class Verdict(BaseModel):
    human_written: bool = Field(
        description="True if a person wrote this unaided. False if a language model wrote or heavily rewrote it."
    )
    confidence: str = Field(description="one of: low, medium, high")
    markers: list[str] = Field(
        default_factory=list,
        description="Specific things in THIS text that led to the verdict. Quote fragments.",
    )
    explanation: str = Field(description="One or two plain sentences the applicant will read.")


INSTRUCTION = """\
You are deciding whether a writing sample was written by a person or generated by
a language model. The sample is being offered as evidence of how someone writes,
so a model-generated sample would poison everything downstream.

Signs it was GENERATED:
- Sentences of near-identical length and shape, paragraph after paragraph.
- Three parallel clauses in a row; lists that are suspiciously balanced.
- Corporate abstractions with nothing concrete underneath: "leverage", "robust",
  "seamless", "passionate about", "delve", "underscore", "pivotal", "moreover".
- Em-dash cadence used for rhythm rather than interruption.
- A tidy closing sentence that restates what was just said.
- No specifics a stranger could not have written: no names, numbers, places, dates.
- Flawless mechanics with no personal habits at all.

Signs a PERSON wrote it:
- Uneven rhythm. A short sentence, then a long rambling one.
- Concrete detail, especially mundane detail: a place, a price, a time of day.
- Typos, inconsistent capitalisation, informal contractions, slang, code-switching
  between languages, repeated pet phrases.
- Thinking visible on the page: self-correction, an aside, a question mid-flow.
- Opinions with an edge, or an admission the writer does not come off well in.

Weigh evidence, do not count keywords. Non-native English is NOT a sign of
generation; it is often the opposite, because a model writes smoother English than
most second-language writers do. Short samples deserve low confidence -- say so
rather than guessing.

Quote actual fragments from the sample in `markers`. A verdict the person cannot
check against their own words is worthless to them.
"""

agent = Agent(
    name="authenticity",
    model=model_id(),
    description="Decides whether a writing sample was written by a person or a model.",
    instruction=INSTRUCTION,
    output_schema=Verdict,
)


async def judge(label: str, text: str) -> Verdict:
    prompt = f"Sample filename: {label}\n\n---\n{text[:14000]}\n---\n\nWho wrote this?"
    return Verdict.model_validate(await run_json(agent, [types.Part(text=prompt)]))
